version: '3'
services: 
    nomeroff:
        build: .
        command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
        environment: 
            # - FLASK_APP=hello.py
            # - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=True
        ports: 
            - "8888:8888"
        # volumes: 
        #     - ./:/nomeroff-net